### PR TITLE
Initial Compatibility for gatesgarth release

### PR DESCRIPTION
**Pull request by soconte**

### CODE REVIEW

**Comment by a-w50** [comment]
Dear @vladzouth ,
thank you for your initial efforts.  I haven't had a look at the gatesgarth release so far.  I will try a test build and come back to this PR.  We've not decided yet if we want to support already EOL'd non-LTS releases of Yocto, because that will mean additional maintainence work.

**Comment by mhei** [comment]
Maybe @vladzouth could elaborate, why supporting gatesgarth would be good? Personally, I also see no benefit in supporting this old release - it not even a LTS one.

**Comment by soconte** [comment]
Hi @a-w50 , 
I make this because we wanted to test this with a project based on this branch. I thought one can use this for testing purpose.

**Comment by a-w50** [comment]
Hi @vladzouth 
I see.  Thank you for sharing this.  But we've decided that we can't support and maintain every Yocto release branch and we'll try to keep up with the LTS branches.  Therefore I'm closing this PR.

Thanks again!

**Pull request closed without merging**
